// Generated by CoffeeScript 1.10.0
(function() {
  var _, universe;

  _ = require('underscore');

  universe = require('./universe');

  require('./future').mixInto(universe);

  require('./canonicalization').mixInto(universe);

  require('./memoization').mixInto(universe);

  require('./gc').mixInto(universe);

  require('./api').mixInto(universe);

  _.defaults(exports, universe);

}).call(this);
